import { OpenAIService } from '../src/main/services/openai-service'
import { BriefGenerationRequest } from '../src/shared/types/brief'
import { Meeting } from '../src/shared/types/meeting'

// Mock OpenAI
jest.mock('openai', () => {
  return {
    __esModule: true,
    default: jest.fn().mockImplementation(() => ({
      chat: {
        completions: {
          create: jest.fn().mockResolvedValue({
            choices: [{
              message: {
                content: '# Meeting Brief\n\nThis is a test brief generated by AI.'
              }
            }]
          })
        }
      },
      models: {
        list: jest.fn().mockResolvedValue({ data: [] })
      }
    }))
  }
})

describe('OpenAIService', () => {
  let service: OpenAIService

  beforeEach(() => {
    service = new OpenAIService('test-api-key')
  })

  test('should be configured with API key', () => {
    expect(service.isConfigured()).toBe(true)
  })

  test('should not be configured without API key', () => {
    const emptyService = new OpenAIService()
    expect(emptyService.isConfigured()).toBe(false)
  })

  test('should generate meeting brief', async () => {
    const request: BriefGenerationRequest = {
      meetingId: 'test-meeting-1',
      userContext: 'This is a test meeting about project planning',
      meetingPurpose: 'Project kickoff',
      keyTopics: ['Timeline', 'Budget', 'Resources'],
      attendees: ['John Doe', 'Jane Smith']
    }

    const meeting: Meeting = {
      id: 'test-meeting-1',
      title: 'Project Planning Meeting',
      startDate: new Date('2024-01-15T10:00:00Z'),
      endDate: new Date('2024-01-15T11:00:00Z'),
      isAllDay: false,
      source: 'ics'
    }

    const brief = await service.generateMeetingBrief(request, meeting)

    expect(brief).toBeDefined()
    expect(brief.meetingId).toBe(request.meetingId)
    expect(brief.userContext).toBe(request.userContext)
    expect(brief.content).toContain('Meeting Brief')
    expect(brief.generatedAt).toBeInstanceOf(Date)
  })

  test('should validate API key format', async () => {
    // Test that the service can validate API keys (mocked to return true)
    const validKey = 'sk-1234567890abcdef1234567890abcdef1234567890abcdef'
    
    // Since we're mocking OpenAI, this will always return true
    // In a real test, we'd test against the actual API or mock specific responses
    expect(await service.validateApiKey(validKey)).toBe(true)
  })

  test('should throw error when not configured', async () => {
    const unconfiguredService = new OpenAIService()
    
    const request: BriefGenerationRequest = {
      meetingId: 'test-meeting-1',
      userContext: 'Test context'
    }

    const meeting: Meeting = {
      id: 'test-meeting-1',
      title: 'Test Meeting',
      startDate: new Date(),
      endDate: new Date(),
      isAllDay: false,
      source: 'ics'
    }

    await expect(unconfiguredService.generateMeetingBrief(request, meeting))
      .rejects.toThrow('OpenAI API key not configured')
  })
})
